name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LISENCE'
    branches:
      - 'master'
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      # - 'release/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30 # consider something went wrong if over
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        docker-compose build
        cp .env.sample .env

    - name: Set up
      run: |
        docker-compose run app make setup

    - name: Lint
      run: |
        docker-compose run app make lint

    - name: Test
      run: |
        docker-compose run app make test
